add-controllers
RikkkiTikkkiTavi/java-shareit pull request #1
Opened 2023-07-14 21:30 UTC by RikkkiTikkkiTavi

2023-07-15 17:38 UTC, sergeymamonov requested changes

2023-07-15 17:38 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/error/ErrorHandler.java
> +    @ResponseStatus(HttpStatus.INTERNAL_SERVER_ERROR)
Ошибка сервера, это когда в коде произошла непредвиденная ошибка. DuplicateEmailException - ошибка которую программист ожидает. Если какая-то сущность уже существует, то возвращают 409 статус код.

2023-07-15 17:38 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/error/ErrorResponse.java
> +    public String getError() {
Одновременно и конструктор, написанный руками, и аннотация Lombok. Конструктор лучше удалить.

2023-07-15 17:38 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/validator/ItemValidator.java
> +        if (!(item.getOwner().getId() == ownerId)) {
Есть знак не равно !=

2023-07-15 17:38 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +    UserStorage storage;
Пропущен модификатор доступа. private final

2023-07-15 17:38 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    ItemStorage itemStorage;
Модификатор доступа.

2023-07-15 18:36 UTC, RikkkiTikkkiTavi commented on src/main/java/ru/practicum/shareit/error/ErrorResponse.java
> +    public String getError() {
Рукописного конструктора не вижу. Геттер на ошибку вижу.

2023-07-17 08:11 UTC, sergeymamonov approved these changes

2023-07-17 08:11 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/error/ErrorResponse.java
> +    public String getError() {
Да, ошибся, имел в виду рукописный геттер, который лучше заменить аннотацией.

2023-07-17 08:29 UTC, merged