Add docker
RikkkiTikkkiTavi/java-shareit pull request #4
Opened 2023-08-26 13:46 UTC by RikkkiTikkkiTavi

2023-08-28 03:47 UTC, sergeymamonov requested changes
Необходимо давать информативные названия коммитам.

В качестве улучшения классы dto можно сделать иммутабельными.

Сервис geteway ErrorHandler в обработчике есть перехват ошибок типа UserNotFound и прочих. Но чтобы кинуть такую ошибку, нужно сделать запрос в БД. Это делается в основном сервисе. А сервис gateway только валидирует входные данные. То есть ошибки ...NotFound не могут возникнуть в gateway. Поэтому и их обработке здесь быть не должно. Нужно обрабатывать только те ошибки, которые могут возникнуть. Аналогично и для основного сервиса. Валидация входных данных должна быть в gateway. Из основного сервиса валидацию входных данных нужно удалить.

ItemRepository - удалить закомментированный код.

По тестам исправление замечаний по желанию. Похожие тесты можно делать параметризированными. Для них можно сделать один параметризированный тест. https://reflectoring.io/tutorial-junit5-parameterized-tests/ Но не настаиваю на этом изменении, а как вариант для улучшения.

2023-08-28 03:47 UTC, sergeymamonov commented on server/src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            throw new ItemValidationException("Комментарий не может быть пустым");
Валидация входных данных должна быть в gateway.

2023-08-28 03:47 UTC, sergeymamonov commented on gateway/src/test/java/ru/practicum/shareit/booking/validator/BookingValidatorTest.java
>          assertThrows(BookingValidateException.class, () -> BookingValidator.checkTime(brd));
Еще можно проверить тест ошибки.

2023-08-28 15:54 UTC, RikkkiTikkkiTavi commented on gateway/src/test/java/ru/practicum/shareit/booking/validator/BookingValidatorTest.java
>          assertThrows(BookingValidateException.class, () -> BookingValidator.checkTime(brd));
Тут немного не понял какой тест проверить.

2023-08-28 16:33 UTC, RikkkiTikkkiTavi commented
Иммутабельность классов обеспечил аннотацией @Value.

Параметризированные тесты буду реализовывать в дипломной работе.

2023-08-29 03:20 UTC, sergeymamonov commented on gateway/src/test/java/ru/practicum/shareit/booking/validator/BookingValidatorTest.java
>          assertThrows(BookingValidateException.class, () -> BookingValidator.checkTime(brd));
текст ошибки*

Извиняюсь, за опечатку))

2023-08-29 03:24 UTC, sergeymamonov approved these changes

2023-09-02 16:00 UTC, merged